services:
  web:
    build: .
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: db_user
      MARIADB_DATABASE: db_feedback
    volumes:
      - ./db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: db_user
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
